sonar.organization=rafliher
sonar.projectKey=rafliher_simpel-upnvj-devsecops
sonar.projectName=simpel-upnvj-devsecops
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/public/css/**,**/public/js/**,**/public/img/**,**/public/font/**,**/public/fonts/**,**/public/icons/**
